# Which is equivalent to
format = """
$username\
$hostname\
$directory\
$git_branch\
$line_break\
$character"""

[python]
disabled=true

[rust]
disabled=true

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[hostname]
ssh_only = false
format = "H:[$ssh_symbol](bold blue)[$hostname](bold red) "
disabled = false

[username]
format = "u:[$user]($style) "
style_user = "cyan"
style_root = "red bold"
disabled = false
show_always = true

[directory]
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo=true
format="[$path]($style)[$read_only]($read_only_style) "
